# Generated by Django 5.2.4 on 2025-08-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='sex',
            new_name='gender',
        ),
    ]
